# Zen - maximum reduction, single character
# white=success, red=error, green=vim-normal
format = "$character"
add_newline = false

[character]
success_symbol = "[·](bold white) "
error_symbol = "[·](bold red) "
vimcmd_symbol = "[·](bold green) "
